```properties
spring.application.name=demoksv

# =========================
# Server
# =========================
server.port=8085


# =========================
# Swagger / OpenAPI
# =========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Keycloak OAuth2 for Swagger
springdoc.swagger-ui.oauth.client-id=employee-api
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true


# =========================
# Spring Security / Keycloak
# =========================
logging.level.org.springframework.security=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/demo


# =========================
# Spring AI
# =========================
spring.ai.openai.api-key=${OPENAI_API_KEY}


# =========================
# Kafka
# =========================
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=my-test-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer